
package com.main;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWebService", targetNamespace = "http://controller.ssh.xrom.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNameV", targetNamespace = "http://controller.ssh.xrom.com/", className = "com.main.GetNameV")
    @ResponseWrapper(localName = "getNameVResponse", targetNamespace = "http://controller.ssh.xrom.com/", className = "com.main.GetNameVResponse")
    @Action(input = "http://controller.ssh.xrom.com/TestWebService/getNameVRequest", output = "http://controller.ssh.xrom.com/TestWebService/getNameVResponse")
    public String getNameV(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
